name: Vanilla
version: '1.1.0'
main: ru.laimcraft.vanilla.Vanilla
api-version: '1.21'
load: STARTUP
authors: [LaimCraft]
depend:
  - CoreProtect
website: https://github.com/LaimCraft/Vanilla
commands:
  chest:
    aliases:
      - chest
      - c
    usage: "/chest <add/remove> <player>"
  get:
    aliases:
      - get
      - getitem
    usage: "/get"
  utpa:
    aliases:
      - utpa
    usage: "/utpa"
  region:
    aliases:
      - region
      - rg
    usage: "/region"
  check:
    aliases:
      - check
    usage: "/check"