name: Vanilla
version: '1.2.0'
main: ru.laimcraft.vanilla.Vanilla
api-version: '1.21.1'
load: STARTUP
authors: [LaimCraft]
depend:
  - CoreProtect
  - VanillaEnchantment
website: https://github.com/LaimCraft/Vanilla
commands:
  home:
    aliases:
      - home
      - h
    usage: "/home"
  sethome:
    aliases:
      - sethome
    usage: "/sethome"
  chest:
    aliases:
      - chest
      - c
    usage: "/chest <add/remove/list> <player>"
  proverka:
    aliases:
      - proverka
    usage: "/proverka"
    permission: laimcraft.vanilla.proverka
  ch:
    aliases:
      - ch
    usage: "/ch"
    permission: laimcraft.vanilla.ch
  adminmode:
      aliases:
        - adminmode
      usage: "/adminmode"
      permission: laimcraft.vanilla.owner
  fly:
      aliases:
        - fly
      usage: "/fly"
      permission: laimcraft.vanilla.fly
  gm:
      aliases:
        - gm
      usage: "/gm"
      permission: laimcraft.vanilla.gm
  kick:
      aliases:
        - kick
      usage: "/kick"
      permission: laimcraft.vanilla.kick
  mute:
    aliases:
      - mute
    usage: "/mute"
    permission: laimcraft.vanilla.mute
  ban:
    aliases:
      - ban
    usage: "/ban"
    permission: laimcraft.vanilla.ban
  stop:
    aliases:
      stop
    usage: "/stop"
    permission: laimcraft.vanilla.stop