name: Vanilla
version: '${version}'
main: ru.laimcraft.vanilla.Core
api-version: '1.21'
load: STARTUP
authors: [LaimCraft]
website: https://github.com/LaimCraft/Vanilla
commands:
  login:
    aliases:
      - login
      - l
    usage: "/login <password>"
  register:
    aliases:
      - register
      - reg
    usage: "/register <password>"