name: Vanilla
version: '1.2.0'
main: ru.laimcraft.vanilla.Vanilla
api-version: '1.21'
load: STARTUP
authors: [LaimCraft]
depend:
  - CoreProtect
website: https://github.com/LaimCraft/Vanilla
commands:
  chest:
    aliases:
      - chest
      - c
    usage: "/chest <add/remove/list> <player>"